### ISSUE TITLE
we've got issues

### ISSUE THREAD

**Issue by GitGud44** [imd1005-web-development-winter-2023/assignment-02-kerosenee#2]
grrrrrr

**Comment by neilmispelaar** [comment]
Oh no! 🙈

**Comment by neilmispelaar** [comment]
Hey @GitGud44 - random question - are you getting notifications when a response to your issue comes in? Trying to see if students are notified when I respond. Thanks so much!

**Comment by GitGud44** [comment]
> Hey @GitGud44 - random question - are you getting notifications when a response to your issue comes in? Trying to see if students are notified when I respond. Thanks so much!

Hey! I did get an email, but only when you tagged me
